### ISSUE TITLE
Looking for the original creators of this mod

### ISSUE THREAD

**Issue by sixsik6** [amokmen/q2ctc#1]
Hey! I'm trying to find the original creators of this mod. The Quake 2 community has shown something of a resurgence since the release of Nightdive Studios Quake 2 Remaster, and there are people looking to curate all Quake 2 mods and maps under one banner so to speak.
It'd be great to have a chat about getting ctc included in this!

**Comment by dergarder** [comment]
Hi. I am not creator of this mod. Even do not know any of them. Just preserved CTC at Github.

You could find their names [here](https://github.com/dergarder/q2ctc#credits).

**Comment by sixsik6** [comment]
No problem. I had a suspicion you weren't, but wasn't sure if it was a screen name for one of the creators. Thanks!
